<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Joseph.Cape
 * Date: 26/07/13
 * Time: 17:24
 * To change this template use File | Settings | File Templates.
 */

//include simplehtml_form.php
require_once('../../config.php');
require_once('simpleajax_mform.php');

global $OUTPUT, $PAGE;

$processing    =   optional_param('processing',0,PARAM_INT);

$new_output = "";

$PAGE->set_context(context_system::instance());

$PAGE->set_url($CFG->wwwroot . '/local/simpleajax_form/simpleajax_form_generator.php');
//Instantiate simplehtml_form
$mform = new simpleajax_form();

if ($fromform = $mform->get_data()) {
    set_config('test-simpleajaxform_email', $fromform->email);
    $new_output = "<br />" . $fromform->email . "<br />";
}

ob_start();
$mform->display();
$formhtml = ob_get_clean();


// AJAX Includes for normal mform Javascript code
// ... First we get the script generated by the Form API

if (strpos($formhtml, '</script>') !== false) {
    $outputparts = explode('</script>', $formhtml);
    $html = $outputparts[1];
    $script = str_replace('<script type="text/javascript">', '', $outputparts[0]);
} else {
    $html = $formhtml;
    $script = '';
}

// Next we get the M.yui.loader call which includes the Javascript libraries
$headcode = $PAGE->requires->get_head_code($PAGE, $OUTPUT);
$loadpos = strpos($headcode, 'M.yui.loader');
$cfgpos = strpos($headcode, 'M.cfg');

$script .= substr($headcode, $loadpos, $cfgpos-$loadpos);
// And finally the initalisation calls for those libraries
$endcode = $PAGE->requires->get_end_code();
$script .= preg_replace('/<\/?(script|link)[^>]*>/', '', $endcode);

if (!$processing) {
    echo json_encode(array('html' => $formhtml, 'script' => $script));
} else {
    echo json_encode(array('new_output'=>$new_output));
}

?>